--- #YAML:1.0
name:               Music-Tag-MusicBrainz
version:            0.4101
abstract:           Plugin module for Music::Tag to get information from MusicBrainz database.
author:
    - Edward Allen (ealleniii _at_ cpan _dot_ org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cache::FileCache:     0
    Music::Tag:           0.4101
    Text::Levenshtein:    0
    WebService::MusicBrainz:  0.07
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
